version: "3.8"

services:

  db:
    container_name: postgres-container
    image: postgres:14.4-alpine
    restart: always
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/postgres.env
    networks:
      - main

  api:
    container_name: fastapi-container
    depends_on:
      - db
    build:
      context: api/.
      dockerfile: Dockerfile
    command: bash -c "
        while !</dev/tcp/db/5432;
        do sleep 1;
        done;
        alembic upgrade head;
        uvicorn app.main:app --host 0.0.0.0 --reload --use-colors
      "
    volumes:
      - ./api/app:/code/app
      - ./api/alembic.ini:/code/alembic.ini
      - ./api/migrations:/code/migrations
    ports:
      - "8000:8000"
    networks:
      - main
    env_file:
      - env/postgres.env

networks:
  main:

volumes:
  postgres_data:
