version: "3.8"

services:

  db:
    container_name: postgres-container
    image: postgres:14.4-alpine
    restart: always
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env/postgres.env
    networks:
      - main

  api:
    container_name: fastapi-container
    build:
      context: api/.
      dockerfile: Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --reload"
    volumes:
      - ./api/app:/code/app
    ports:
      - "8000:8000"
    networks:
      - main

networks:
  main:

volumes:
  postgres_data:
