"""Added ondelete behavior to task.user_id

Revision ID: 06ab255a2608
Revises: a970eb2934ab
Create Date: 2022-07-12 22:46:37.520430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ab255a2608'
down_revision = 'a970eb2934ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_user_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_user_id_fkey', 'task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
