"""Create Reminder table, set up relations

Revision ID: 0f28987b85b4
Revises: 06ab255a2608
Create Date: 2022-07-13 01:23:41.588588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f28987b85b4'
down_revision = '06ab255a2608'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('via_email', sa.Boolean(), nullable=False),
    sa.Column('via_telegram', sa.Boolean(), nullable=False),
    sa.Column('remind_on', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_remind_on'), 'reminder', ['remind_on'], unique=False)
    op.add_column('user', sa.Column('telegram', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_user_telegram'), 'user', ['telegram'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram'), table_name='user')
    op.drop_column('user', 'telegram')
    op.drop_index(op.f('ix_reminder_remind_on'), table_name='reminder')
    op.drop_table('reminder')
    # ### end Alembic commands ###
