"""Added registered_on, data_of_birth columns to user model and created_on to task model

Revision ID: a970eb2934ab
Revises: 508e8449942e
Create Date: 2022-07-12 21:28:38.611055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a970eb2934ab'
down_revision = '508e8449942e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('task', 'is_checked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('data_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'data_of_birth')
    op.drop_column('user', 'registered_on')
    op.alter_column('task', 'is_checked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('task', 'created_on')
    # ### end Alembic commands ###
