"""Init

Revision ID: d6c1db008356
Revises: 
Create Date: 2022-07-20 01:31:42.706977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c1db008356'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_type_type'), 'reminder_type', ['type'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('telegram', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('registered_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_index(op.f('ix_user_telegram'), 'user', ['telegram'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('due', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reminder_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reminder_type_id'], ['reminder_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_due'), 'task', ['due'], unique=False)
    op.create_index(op.f('ix_task_is_checked'), 'task', ['is_checked'], unique=False)
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_index(op.f('ix_task_is_checked'), table_name='task')
    op.drop_index(op.f('ix_task_due'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_user_telegram'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_reminder_type_type'), table_name='reminder_type')
    op.drop_table('reminder_type')
    # ### end Alembic commands ###
